Repository LM-channel-team-project/team10-op.gg-clone, pull requests merged in 2021-04, with the labels that each got.

#4 issues, pr 템플릿 추가
  .github/ISSUE_TEMPLATE/Bug_Report.md
  .github/ISSUE_TEMPLATE/Questions.md
  .github/ISSUE_TEMPLATE/Suggestions.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :zap: 심플

#6 [ADD] feature 작성용 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/New_Feature.md
Labels: :eyes: 리뷰 필요, :memo: 문서

#7 헤더 컴포넌트 추가
  public/assets/headerLogo/battle-logo.svg
  public/assets/headerLogo/fortnite-logo.svg
  public/assets/headerLogo/lol-logo.svg
  public/assets/headerLogo/overwatch-logo.svg
  public/assets/headerLogo/rainbow-six-logo.svg
  src/components/Footer/Footer.tsx
  src/components/Footer/index.ts
  src/components/Header/Header.tsx
  src/components/Header/HeaderGnb/GnbNavItem.tsx
  src/components/Header/HeaderGnb/HeaderGnb.tsx
  src/components/Header/HeaderGnb/HeaderLogo.tsx
  src/components/Header/HeaderGnb/index.ts
  src/components/Header/HeaderGnb/style.ts
  src/components/Header/HeaderMenu/HeaderMenu.tsx
  src/components/Header/HeaderMenu/MenuItem.tsx
  src/components/Header/HeaderMenu/index.ts
  src/components/Header/HeaderMenu/style.ts
  src/components/Header/index.ts
  src/components/Layout/Layout.tsx
  src/lib/static/headerMeta.ts
  src/lib/styles/palette.ts
  src/types/header.d.ts
Labels: :eyes: 리뷰 필요, :wrench: 기능

#9 champion 페이지 ChampionRankTable 컴포넌트 추가
  .gitignore
  public/assets/champions/champion32.png
  public/assets/champions/icon-champion-n.png
  public/assets/champions/icon-championtier-stay.png
  src/api/champion/rank/banRate.ts
  src/api/champion/rank/pickRate.ts
  src/api/champion/rank/tier.ts
  src/api/champion/rank/winRate.ts
  src/components/Champions/ContentMain/ChampionList/ChampionCard/ChampionCard.tsx
  src/components/Champions/ContentMain/ChampionList/ChampionCard/styles.ts
  src/components/Champions/ContentMain/ChampionList/ChampionList.tsx
  src/components/Champions/ContentSide/ContentSide.tsx
  src/components/Champions/ContentSide/ContentSideList/ChampionRankTable/ChampionRankTable.tsx
  src/components/Champions/ContentSide/ContentSideList/ChampionRankTable/RankTableBody.tsx
  src/components/Champions/ContentSide/ContentSideList/ChampionRankTable/index.ts
  src/components/Champions/ContentSide/ContentSideList/ChampionRankTable/styles.ts
  src/components/Champions/ContentSide/ContentSideList/ChampionRankTable/types.ts
  src/components/Champions/ContentSide/ContentSideList/ContentSideList.tsx
  src/components/Champions/ContentSide/ContentSideList/TabHeader/TabHeader.tsx
  src/components/Champions/ContentSide/ContentSideList/TabHeader/index.ts
  src/components/Champions/ContentSide/ContentSideList/TabHeader/styles.ts
  src/components/Champions/ContentSide/ContentSideList/TabHeader/types.ts
  src/components/Champions/ContentSide/ContentSideList/index.ts
  src/components/Champions/ContentSide/ContentSideList/styles.ts
  src/components/Champions/ContentSide/ContentSideList/types.ts
  src/components/Champions/ContentSide/ContentSideList/useSelectedTabItem.ts
  src/components/Champions/ContentSide/ContentSideNavbar/ContentSideNavbar.tsx
  src/components/Champions/ContentSide/ContentSideNavbar/index.ts
  src/components/Champions/ContentSide/ContentSideNavbar/styles.ts
  src/components/Champions/ContentSide/ContentSideNavbar/types.ts
  src/components/Champions/ContentSide/styles.ts
  src/components/Champions/index.tsx
  src/components/Champions/style.ts
  src/components/Champions/types.ts
  src/pages/champions/index.tsx
  src/pages/champions/style.ts
Labels: :eyes: 리뷰 필요, :wrench: 기능

#10 챔피언 상세보기 ([champion]) 헤더 영역 및 네비게이션 컴포넌트 추가
  package-lock.json
  package.json
  src/components/ChampionDetails/ChampionDetailsHeader/ChampionDetailsHeader.tsx
  src/components/ChampionDetails/ChampionDetailsHeader/TabItems/Items.ts
  src/components/ChampionDetails/ChampionDetailsHeader/TabItems/TabCounter/CounterData.ts
  src/components/ChampionDetails/ChampionDetailsHeader/TabItems/TabCounter/TabCounter.tsx
  src/components/ChampionDetails/ChampionDetailsHeader/TabItems/TabCounter/index.tsx
  src/components/ChampionDetails/ChampionDetailsHeader/TabItems/TabEasy/EasyData.ts
  src/components/ChampionDetails/ChampionDetailsHeader/TabItems/TabEasy/TabEasy.tsx
  src/components/ChampionDetails/ChampionDetailsHeader/TabItems/TabEasy/index.tsx
  src/components/ChampionDetails/ChampionDetailsHeader/TabItems/TabItems.tsx
  src/components/ChampionDetails/ChampionDetailsHeader/TabItems/index.tsx
  src/components/ChampionDetails/ChampionDetailsHeader/TabItems/styles.ts
  src/components/ChampionDetails/ChampionDetailsHeader/index.tsx
  src/components/ChampionDetails/ChampionDetailsHeader/styles.ts
  src/components/ChampionDetails/ChampionDetailsMain/ChampionDetailsMain.tsx
  src/components/ChampionDetails/ChampionDetailsMain/ChampionDetailsNav/ChampionDetailsFilterItems.ts
  src/components/ChampionDetails/ChampionDetailsMain/ChampionDetailsNav/ChampionDetailsNav.tsx
  src/components/ChampionDetails/ChampionDetailsMain/ChampionDetailsNav/index.tsx
  src/components/ChampionDetails/ChampionDetailsMain/ChampionDetailsNav/styles.ts
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentAll/DetailsContentAll.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentAll/index.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentAll/styles.ts
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentCounter/DetailsContentCounter.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentCounter/index.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentCounter/styles.ts
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentItem/DetailsContentItem.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentItem/index.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentItem/styles.ts
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentRune/DetailsContentRune.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentRune/index.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentRune/styles.ts
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentSkill/DetailsContentSkill.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentSkill/index.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentSkill/styles.ts
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentTip/DetailsContentTip.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentTip/index.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentTip/styles.ts
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentTrend/DetailsContentTrend.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentTrend/index.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentTrend/styles.ts
  src/components/ChampionDetails/ChampionDetailsMain/index.tsx
  src/components/ChampionDetails/ChampionDetailsMain/style.ts
  src/components/Layout/Layout.tsx
  src/pages/champions/[champion].tsx
  tsconfig.json
Labels: :+1: 리뷰 완료, :computer: 개발 중, :wrench: 기능

#12 푸터 컴포넌트, 아이콘 컴포넌트 추가
  package.json
  public/assets/svg/battle-logo.svg
  public/assets/svg/fortnite-logo.svg
  public/assets/svg/github-logo.svg
  public/assets/svg/index.ts
  public/assets/svg/lol-logo.svg
  public/assets/svg/overwatch-logo.svg
  public/assets/svg/rainbow-six-logo.svg
  public/assets/svg/youtube-logo.svg
  src/components/Common/Icon/Icon.tsx
  src/components/Common/Icon/index.ts
  src/components/Footer/Footer.tsx
  src/components/Footer/FooterItem.tsx
  src/components/Footer/style.ts
  src/components/Header/HeaderGnb/HeaderGnb.tsx
  src/components/Header/HeaderGnb/style.ts
  src/components/Header/HeaderMenu/style.ts
  src/components/Layout/Layout.tsx
  src/lib/static/basicMeta.ts
  src/lib/static/headerMeta.ts
  yarn.lock
Labels: :eyes: 리뷰 필요, :wrench: 기능

#13 메타 태그 컴포넌트 추가, 타이틀 컴포넌트 추가
  public/assets/logo/meta-og-image.png
  src/components/Helmet/Helmet.tsx
  src/components/Helmet/index.ts
  src/components/Title/Title.tsx
  src/components/Title/index.ts
  src/lib/static/metaTagData.ts
  src/pages/_app.tsx
Labels: :wrench: 기능, :zap: 심플

#18 Champions 페이지 로테이션 UI, 검색, 링크 기능 추가
  package-lock.json
  package.json
  src/components/Champions/ContentMain/ChampionList/ChampionCard/ChampionCard.tsx
  src/components/Champions/ContentMain/ChampionList/ChampionCard/styles.ts
  src/components/Champions/ContentMain/ChampionList/ChampionList.tsx
  src/components/Champions/ContentMain/ContentMain.tsx
  src/components/Champions/ContentSide/ContentSideList/ChampionRankTable/RankTableBody.tsx
  src/components/Champions/ContentSide/ContentSideList/ChampionRankTable/types.ts
  src/components/Champions/style.ts
  src/components/Champions/types.ts
  src/lib/static/championsMeta.ts
  src/pages/champions/index.tsx
Labels: :eyes: 리뷰 필요, :wrench: 기능

#20 아이템 탭 구현
  src/components/ChampionDetails/ChampionDetailsHeader/ChampionDetailsHeader.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentAll/ItemTable/ItemTable.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentAll/SpellAndSkillTable/SpellAndSkillTable.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentItem/BootsTable/BootsTable.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentItem/BootsTable/index.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentItem/CoreTable/CoreTable.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentItem/CoreTable/index.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentItem/DetailsContentItem.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentItem/SideTable/SideTable.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentItem/SideTable/index.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentItem/StartItemTable/StartItemTable.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentItem/StartItemTable/index.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentItem/itemData.ts
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentItem/styles.ts
  yarn.lock
Labels: :eyes: 리뷰 필요, :wrench: 기능

#21 메인 페이지 추가 ( 지역 및 언어 모달, 광고 배너, 커뮤니티)
  next.config.js
  public/assets/logo/main-page-logo.png
  public/assets/region/btn-check-off.png
  public/assets/region/btn-check-on.png
  public/assets/region/btn-modalClose.png
  public/assets/region/mark-beta.png
  public/assets/region/regionFlag-br.png
  public/assets/region/regionFlag-eune.png
  public/assets/region/regionFlag-euw.png
  public/assets/region/regionFlag-id.png
  public/assets/region/regionFlag-jp.png
  public/assets/region/regionFlag-kr.png
  public/assets/region/regionFlag-lan.png
  public/assets/region/regionFlag-las.png
  public/assets/region/regionFlag-na.png
  public/assets/region/regionFlag-oce.png
  public/assets/region/regionFlag-ph.png
  public/assets/region/regionFlag-ru.png
  public/assets/region/regionFlag-sg.png
  public/assets/region/regionFlag-th.png
  public/assets/region/regionFlag-tr.png
  public/assets/region/regionFlag-tw.png
  public/assets/region/regionFlag-vn.png
  src/components/Home/Home.tsx
  src/components/Home/HomeAdsBanner.tsx
  src/components/Home/HomeCommunty/HomeCommunity.tsx
  src/components/Home/HomeCommunty/HomeCommunityItem.tsx
  src/components/Home/HomeCommunty/index.ts
  src/components/Home/HomeCommunty/style.ts
  src/components/Home/HomeRegionLangModal/HomeRegionLangContent.tsx
  src/components/Home/HomeRegionLangModal/HomeRegionLangLayer.tsx
  src/components/Home/HomeRegionLangModal/HomeRegionLangModal.tsx
  src/components/Home/HomeRegionLangModal/HomeRegionLangRadio.tsx
  src/components/Home/HomeRegionLangModal/HomeRegionLangSubmit.tsx
  src/components/Home/HomeRegionLangModal/index.ts
  src/components/Home/HomeRegionLangModal/style.ts
  src/components/Home/HomeSearchForm/HomeRegionLangButton.tsx
  src/components/Home/HomeSearchForm/HomeSearchForm.tsx
  src/components/Home/HomeSearchForm/HomeSearchInput.tsx
  src/components/Home/HomeSearchForm/index.ts
  src/components/Home/HomeSearchForm/style.ts
  src/components/Home/index.ts
  src/components/Home/style.ts
  src/components/Layout/Layout.tsx
  src/contexts/RegionLangContext.tsx
  src/hooks/useDebounce.ts
  src/hooks/useInputs.ts
  src/lib/static/regionLanguageMeta.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/types/regionLanguage.d.ts
Labels: :+1: 리뷰 완료, :wrench: 기능

#22 스킬 탭(ChampionDetailsMain/DetailsContents/DetailsContentsSkill) 구현
  src/components/ChampionDetails/ChampionDetailsMain/ChampionDetailsMain.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentAll/ItemTable/ItemTable.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentAll/SideItems/styles.ts
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentAll/SpellAndSkillTable/ChampionSkillBuildTable/ChampionSkillBuildTable.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentAll/SpellAndSkillTable/ChampionSkillBuildTable/styles.ts
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentAll/SpellAndSkillTable/SpellAndSkillTable.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentItem/CoreTable/CoreTable.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentItem/StartItemTable/StartItemTable.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentSkill/DetailsContentSkill.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentSkill/styles.ts
  src/components/ChampionDetails/championDetailsInfo.ts
Labels: :wrench: 기능, :zap: 심플

#24 HoverContainer 추가
  src/components/Champions/ContentSide/ContentSideList/ChampionRankTable/ChampionRankTable.tsx
  src/components/Champions/ContentSide/ContentSideList/ChampionRankTable/styles.ts
  src/components/Champions/index.tsx
  src/components/Champions/style.ts
  src/components/Common/HoverContainer/HoverContainer.tsx
  src/components/Common/HoverContainer/index.ts
  src/components/Common/HoverContainer/styles.ts
Labels: :eyes: 리뷰 필요, :wrench: 기능

#25 룬 탭(ChampionDetailsMain/DetailsContents/DetailsContentsRune)
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentRune/DetailsContentRune.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentRune/RuneTable/RuneTable.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentRune/RuneTable/index.tsx
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentRune/RuneTable/styles.ts
  src/components/ChampionDetails/ChampionDetailsMain/DetailsContents/DetailsContentRune/styles.ts
  src/components/ChampionDetails/championDetailsInfo.ts
Labels: :wrench: 기능, :zap: 심플

#28 메인페이지 검색 자동 완성 추가
  next.config.js
  src/components/Home/HomeSearchForm/HomeSearchForm.tsx
  src/components/Home/HomeSearchForm/style.ts
  src/components/SearchExtra/SearchAutoComplete/SearchAutoComplete.tsx
  src/components/SearchExtra/SearchAutoComplete/SearchAutoCompleteError.tsx
  src/components/SearchExtra/SearchAutoComplete/SearchAutoCompleteItem.tsx
  src/components/SearchExtra/SearchAutoComplete/index.ts
  src/components/SearchExtra/SearchAutoComplete/style.ts
  src/components/SearchExtra/SearchExtra.tsx
  src/components/SearchExtra/SearchHistory/SearchHistory.tsx
  src/components/SearchExtra/SearchHistory/index.ts
  src/components/SearchExtra/SearchHistory/style.ts
  src/components/SearchExtra/index.ts
  src/components/SearchExtra/style.ts
  src/hooks/swr/useSummoner.ts
  src/lib/api/Summoner/getLeagueEntry.ts
  src/lib/api/Summoner/getSummoner.ts
  src/lib/api/Summoner/index.ts
  src/pages/summoners/[summoner].tsx
  src/pages/summoners/index.tsx
  src/types/summoner.d.ts
Labels: :eyes: 리뷰 필요, :wrench: 기능
